### ISSUE TITLE
Produciton Report Forms missing in Mobile Screen

### ISSUE THREAD

**Issue by ksdhir** [Haidoe/arc#107]
## Produciton Report Forms missing in Mobile Screen

**Reporter: ❗️**
 @StephanyJade 

**Describe the bug: ❗️**
When production report page is accessed on mobile the sidebar takes the whole page and the forms are missing.

**Steps to reproduce: ❗️**
1. Go to '[Home Page'](https://arc-app.ca/home)
2. Click on 'Any existing production'
3. Change the browser window to 'mobile view'
4. See the forms are no longer visible.

**Screenshots or Video**

***With  Sidebar opened***
![Screenshot 2023-07-16 at 9 15 38 PM](https://github.com/Haidoe/arc/assets/44022086/31b8fc68-2b5b-473a-b6b9-e54208a2ecad)

***With Sidebar closed***
![Screenshot 2023-07-16 at 9 16 13 PM](https://github.com/Haidoe/arc/assets/44022086/0783acc6-cd59-4170-9641-b22c2d877561)

**Expected behavior:  ❗️**
The layout should look like this:
![Screenshot 2023-07-16 at 9 33 40 PM](https://github.com/Haidoe/arc/assets/44022086/09c72a8f-f9ae-4dd3-925b-8120bdcb9da5)

**Actual behavior:  ❗️**
The sidebar takes the whole window and somehow the forms are still missing even if the sidebar is closed.

**Follow up checklist:  ❗️**
- [x]  Add Assignee
- [x]  Label priority ( priority-low, priority-medium, priority-high )
- [x]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
This has been resolved in dev
