### ISSUE TITLE
Not able to see the splash screen

### ISSUE THREAD

**Issue by StephanyJade** [Haidoe/arc#113]
## Bug Report

**Reporter: ❗️**
 @StephanyJade 

**Describe the bug: ❗️**
I wasn’t able to check the splash screen for desktop but maybe is because I'm checking it in a browser.

**Screenshots or Video**
<img width="910" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/edd30a65-7c32-4c34-83a5-790080464a49">

**Expected behavior:  ❗️**
Once the user clicks sign in from the navigation menu on the landing page, they can see the splash screen for a few seconds.

**Actual behavior:  ❗️**
No splash screen.

**Possible Solution:**
If you have any ideas or suggestions on how to fix the bug, please mention them here.

**Environment:**
- Device & Operating System:
- Browser and Version(if applicable):

**Additional context:**
NOTE: This might not be a bug to fix or might in process.

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
Hi @StephanyJade 

Usually, web apps don't have splash screens.

Will close this
