### ISSUE TITLE
Login input fields validation missing

### ISSUE THREAD

**Issue by StephanyJade** [Haidoe/arc#114]
## Bug Report

**Reporter: ❗️**
 @StephanyJade 

**Describe the bug: ❗️**
The login form doesn’t show the error messages when the user is using wrong information to login. 

**Steps to reproduce: ❗️**
1. Type random email
2. Type random password
3. Click login CTA
4. See that the form refreshes but not display validation messages.

**Screenshots or Video**
<img width="677" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/367bd43f-71b2-41db-84b9-cc6ebb608828">

**Expected behavior:  ❗️**
When typing wrong information the validation should display a general instruction message.

**Actual behavior:  ❗️**
The form refreshes but doesn't show validation messages.

**Possible Solution:**
Please follow the design guide: **UI Kit** / **01_UIFields** on figma file: https://www.figma.com/file/LI4LTcsiA7zSuVv20TRVso/UX%2FUI-Material?type=design&node-id=564-3638&mode=design&t=FylHis7j85antdtG-0
<img width="289" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/7d6cc3f1-ac6e-40f2-aeb3-98ad1f12f2af">

**Additional context:**
Add generic messages for validation.

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [x]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
Hi @StephanyJade 

This is not part of the flow.
