### ISSUE TITLE
Missing placeholders in login form (Check this issue in all forms)

### ISSUE THREAD

**Issue by StephanyJade** [Haidoe/arc#115]
## Bug Report

**Reporter: ❗️**
 @StephanyJade 

**Describe the bug: ❗️**
The login form doesn’t have placeholders for the input fields.

**Screenshots or Video**
<img width="564" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/d1b15c59-f6bf-40f0-a94e-55e6bd4b809e">

**Additional context:**
Check placeholders in all the forms (Except the reports page).

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [x]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
Resolved it with this ticket.

https://github.com/Haidoe/arc/issues/130

@StephanyJade
