### ISSUE TITLE
Missing flows: Forgot Password and Create an account

### ISSUE THREAD

**Issue by StephanyJade** [Haidoe/arc#116]
## Bug Report

**Reporter: ❗️**
 @StephanyJade 

**Describe the bug: ❗️**
The Forgot Password and Create and account CTA in the login page are not working, therefore I couldn’t test the flow.

**Steps to reproduce: ❗️**
1. Click on Forgot Password
2. Click on Don't have an account? Create one

**Screenshots or Video**
<img width="478" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/a0267de4-0d8c-44cf-a234-aa79654b454a">

**Expected behavior:  ❗️**
Each CTA should open their corresponding flow.

**Actual behavior:  ❗️**
CTAs are disable.

**Additional context:**
Please add the underline to indicate hyperlinks. Design reference:
<img width="530" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/f196e1da-bb3f-4362-b711-6f00c7aa20cf">

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [x]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
Hi @StephanyJade ,

We really don't have flow for that part (forgot and creation of account). 
We only have Google sign in.

For the underline style update, you can test it here:
https://arc-git-dev-haidoe.vercel.app/sign-in
