### ISSUE TITLE
Missing flow: Production page

### ISSUE THREAD

**Issue by StephanyJade** [Haidoe/arc#117]
## Bug Report

**Reporter: ❗️**
 @StephanyJade 

**Describe the bug: ❗️**
Missing Project page flow

**Steps to reproduce: ❗️**
1. Click on create a new production

**Screenshots or Video**
<img width="1671" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/8ea8ad83-65d0-417e-810c-161bccc6c434">

**Expected behavior:  ❗️**
By clicking **New Production** they user should be able to follow the flow designed for creating a new project. 

**Actual behavior:  ❗️**
The **New Production**  CTA duplicates an existing project

**Environment:**
- Browser and Version(if applicable): Google Chrome

**Additional context:**
I couldn’t test the Production page because the pages for creating a new production are missing. Please follow the designed flow **WIP_UI WEB Mockup & Prototype** / **Productions / Create New Productions**: 
<img width="900" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/d33a7876-44cb-4db4-ae14-5a97be412a45">

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [x]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
Production userflow will not be implemented

**Comment by StephanyJade** [comment]
Got it! Thank you.
