### ISSUE TITLE
Not able to delete or edit productions 

### ISSUE THREAD

**Issue by StephanyJade** [Haidoe/arc#118]
## Bug Report

**Reporter: ❗️**
 @StephanyJade 

**Describe the bug: ❗️**
Since we don’t have the production page working, I'm not able to delete or edit any existing project.

**Expected behavior:  ❗️**
Create a new production, log the information and save. After that, edit or delete if necessary.

**Actual behavior:  ❗️**
One existing production that keeps duplicating.

**Additional context:**
Related to ticket https://github.com/Haidoe/arc/issues/117

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
Hi @StephanyJade 

This will not be part of the demo.
