### ISSUE TITLE
Report page - Alignments and spacings

### ISSUE THREAD

**Issue by StephanyJade** [Haidoe/arc#119]
## Bug Report

**Reporter: ❗️**
 @StephanyJade 

**Describe the bug: ❗️**
There's some misaligned elements or some weird spacing in the layout. Specially between the side menu and the navigation menu.

**Steps to reproduce: ❗️**

**Screenshots or Video**
<img width="843" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/987f8fc7-c0ea-4eb5-935b-3f778730932a">

**Expected behavior:  ❗️**
All elements have consistent spacing and alignment.
Example of expected alignment: 
<img width="828" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/0148b0cf-7140-4eb5-98ca-d8da28e3fe53">

**Actual behavior:  ❗️**
Some discrepancies.

**Additional context:**
This is a design issue to be solved first in the mockups: https://www.figma.com/file/LI4LTcsiA7zSuVv20TRVso/UX%2FUI-Material?type=design&node-id=917-9718&mode=design&t=FylHis7j85antdtG-0

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
this is fixed by @ksdhir
