### ISSUE TITLE
Report page - Schedule form

### ISSUE THREAD

**Issue by StephanyJade** [Haidoe/arc#120]
## Bug Report

**Reporter: ❗️**
 @StephanyJade 

**Describe the bug: ❗️**
This form has simple information so it should be displayed in the small size of the forms.

**Screenshots or Video**
<img width="1310" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/45e7de0a-2243-4d10-8449-689273cb21bc">

**Expected behavior:  ❗️**
Change the form to be half the size (Follow the mockups).

**Actual behavior:  ❗️**
The form is full size and it looks odd because there's just a few information to be displayed full width.

**Additional context:**
Please follow mockups design: 
<img width="885" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/b79cd510-0f19-45cd-9708-d6a24a4a70ba">

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
this is fixed by @jbsinluenam
