### ISSUE TITLE
Report page - Cast time log schedule form

### ISSUE THREAD

**Issue by StephanyJade** [Haidoe/arc#122]
## Bug Report

**Reporter: ❗️**
 @StephanyJade 

**Describe the bug: ❗️**
The form needs to have the information disclaimer at the bottom since contains conventions.

**Screenshots or Video**
<img width="1238" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/b1299656-6204-4f2f-8f77-bb8fa43e3a26">

**Expected behavior:  ❗️**
Have conventions disclaimer message

**Actual behavior:  ❗️**
No instructions for filling the conventions fields.

**Additional context:**
Please follow the mockups
<img width="845" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/71eb8db1-4dac-46c8-9ab7-e6d1ec0a5825">

**Follow up checklist:  ❗️**
- [x]  Add Assignee
- [x]  Label priority ( priority-low, priority-medium, priority-high )
- [x]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by ksdhir** [comment]
@StephanyJade please test and close.

**Comment by StephanyJade** [comment]
Tested and approved! Thanks
