### ISSUE TITLE
Report page - Edit cast time schedule form

### ISSUE THREAD

**Issue by StephanyJade** [Haidoe/arc#123]
## Bug Report

**Reporter: ❗️**
 @StephanyJade 

**Describe the bug: ❗️**
The form has the functionality of editing but no icons to indicate the user that they can edit single lines.

**Screenshots or Video**
<img width="289" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/a07cac1f-c2b4-4b11-b8b0-1f45404e6f6f">

**Expected behavior:  ❗️**
Each line needs to have the edit icon to follow common user experience.

**Actual behavior:  ❗️**
There's no edit icons in the form.

**Additional context:**
Please follow the design and add icons in each line (No a general edit button).
<img width="144" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/f76ec59b-1942-4ec5-b1f3-95f3fa4c8b62">

**Follow up checklist:  ❗️**
- [x]  Add Assignee
- [x]  Label priority ( priority-low, priority-medium, priority-high )
- [x]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
@rjung07 
Please provide how it looks like (pictures) and colors

CC: @ksdhir

**Comment by rafaelajung** [comment]
![image](https://github.com/Haidoe/arc/assets/123789857/91536602-04c2-43e6-befd-826029722868)

Use the icons on the inactive state as **light grey #AAAAAA**
Use the delete icon on hover state as **red #CB3F3F**
Use the edit icon on hover state as **turquoise ##358B98**

**Comment by ksdhir** [comment]
@StephanyJade the issue title mentions "cast time schedule form"; but I think you want to update all forms with CRUD functionality.
Nevertheless I'm going to update all those forms so design is consistent.

**Comment by ksdhir** [comment]
@StephanyJade @rjung07 

This was partially fixed, the functionality is added but icons are different. You guys can test it now, but do not close it.
I'll close it after I get the correct icons.

**Comment by ksdhir** [comment]
Fixed and Closing this now.
