### ISSUE TITLE
Report page - preview and download CTA

### ISSUE THREAD

**Issue by StephanyJade** [Haidoe/arc#124]
## Bug Report

**Reporter: ❗️**
 @StephanyJade 

**Describe the bug: ❗️**
Missing preview and download CTA in the report page.

**Screenshots or Video**
<img width="647" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/775ced3f-3f9e-4aa3-8713-aa988830743a">

**Expected behavior:  ❗️**
Add the CTAs and functionality for each one.

**Actual behavior:  ❗️**
No CTAs to finish the report process.

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by ksdhir** [comment]
Out of scope - Wouldn't be doing this for the demo or prototype. So closing it.
