### ISSUE TITLE
chore: behavior of time input field in Cast Time Log

### ISSUE THREAD

**Issue by jbsinluenam** [Haidoe/arc#126]
## Bug Report

**Reporter: ❗️**
 @jbsinluenam 

**Describe the bug: ❗️**
Once user clicked add new line, all of input field automatically change to 4:00pm.

**Steps to reproduce: ❗️**
1. Go to 'report page' and Cast Time Log form
2. Click on 'Create new line' and click 'Add.
3. See error

**Screenshots or Video**
If applicable, add screenshots / video to help explain your problem.

**Expected behavior:  ❗️**

**Actual behavior:  ❗️**
A clear and concise description of what actually happened.

**Possible Solution:**
If you have any ideas or suggestions on how to fix the bug, please mention them here.

**Environment:**
- Device & Operating System:
- Browser and Version(if applicable):
- Jira Ticket(if applicable):
- Any other relevant information about your environment.

**Additional context:**

**Follow up checklist:  ❗️**
- [x]  Add Assignee
- [x]  Label priority ( priority-low, priority-medium, priority-high )
- [x]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by ksdhir** [comment]
@jbsinluenam 
This was fixed please test and verify.

**Comment by jbsinluenam** [comment]
All of the input is required now, but when i click outside the modal, the form is still allow me to add the new row without data. Try it.

**Comment by ksdhir** [comment]
@jbsinluenam Thanks for testing. Working on this now.

**Comment by ksdhir** [comment]
@jbsinluenam I think when you click outside, the modal closes. But never adds a new row. Could you check again?

**Comment by jbsinluenam** [comment]
Fixed.
