### ISSUE TITLE
Icon: Weird Left arrow on Side Bar

### ISSUE THREAD

**Issue by jbsinluenam** [Haidoe/arc#128]
## Bug Report

**Reporter: ❗️**
 @jbsinluenam 

**Describe the bug: ❗️**
Left arrow icon on Side Bar looks distort, or dispoportion

**Steps to reproduce: ❗️**

**Screenshots or Video**
![1689624772941](https://github.com/Haidoe/arc/assets/88930141/316cd06c-5b3b-4323-92ab-ecbd468b928e)

**Expected behavior:  ❗️**
![1689624886135](https://github.com/Haidoe/arc/assets/88930141/c724bd0d-59c1-4fce-a1da-8cadf5daac0f)

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by StephanyJade** [comment]
@rjung07 
cc: @wakapix @kbmirambel 

Please change the button or present a new proposal.

Thank you.

**Comment by rafaelajung** [comment]
@StephanyJade and @jbsinluenam 

It was already different on the design page. I talked to @Haidoe to change it already. This is how it looks in the mockup.
![image](https://github.com/Haidoe/arc/assets/123789857/1d96874b-1fce-4c39-b44a-731df3f762d5)

**Comment by rafaelajung** [comment]
@jbsinluenam and @Haidoe 

Please, follow this option.

![image](https://github.com/Haidoe/arc/assets/123789857/743dbff8-2ca4-4bdf-90f0-5f344aa3425b)

**Comment by Haidoe** [comment]
@rjung07 will it become purple?
