### ISSUE TITLE
Sign In not working (mobile)

### ISSUE THREAD

**Issue by kbmirambel** [Haidoe/arc#131]
**Reporter: ❗️**
 @kbmirambel 

**Describe the bug: ❗️**
Button of sign in is not working on mobile

**Steps to reproduce: ❗️**
1. After clicking the Sign In button from the hamburger menu, it's not loading

**Screenshots or Video**
![IMG_0101](https://github.com/Haidoe/arc/assets/123606372/cb602937-10f1-480f-b6ae-6badd204abe2)

**Expected behavior:  ❗️**
Proceed to Log In page

**Actual behavior:  ❗️**
Not loading

**Environment:**
- Device & Operating System: Mobile (Safari & Chrome)

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
@ksdhir  you can apply on the mobile nav what I implemented on the desktop nav.

**Comment by ksdhir** [comment]
@Haidoe thanks for the heads up!

**Comment by ksdhir** [comment]
This was fixed under https://github.com/Haidoe/arc/commit/485fa9051ae6047210cd7992673005a685f24ba3

@kbmirambel Please test / verify and close this.
