### ISSUE TITLE
style: consistency of padding in each form

### ISSUE THREAD

**Issue by jbsinluenam** [Haidoe/arc#132]
## Bug Report

**Reporter: ❗️**
 @jbsinluenam 

**Describe the bug: ❗️**
No consistency of padding

**Steps to reproduce: ❗️**
1. Go to Report Page

**Screenshots or Video**
![1689647001512](https://github.com/Haidoe/arc/assets/88930141/b7a969f2-71e2-4595-95c6-20470a41548c)

**Expected behavior:  ❗️**
All should be equal or close.

**Possible Solution:**
Decide which one is the correct padding and try to match that one.

**Environment:**
- Device & Operating System:
- Browser and Version(if applicable):
- Jira Ticket(if applicable):
- Any other relevant information about your environment.

**Additional context:**

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
Hi @rjung07,

Please provide the proper padding.

CC: @jbsinluenam

**Comment by rafaelajung** [comment]
Hi @Haidoe 

the padding should be 
**top & bottom 24px
left and right 16px**

spacing between lines and sections on a card should follow the Figma file orientation. Let me know when you are planning to change this and I will try to guide and help you.

**Comment by jbsinluenam** [comment]
the padding should be
top & bottom 24px
left and right 16px
- fixed
