### ISSUE TITLE
chore: Placeholder in Schedule of The Day

### ISSUE THREAD

**Issue by jbsinluenam** [Haidoe/arc#133]
## Bug Report

**Reporter: ❗️**
 @jbsinluenam 

**Describe the bug: ❗️**
Placeholder in Holiday fields in Schedule of The Day Modal are missing.

**Steps to reproduce: ❗️**
1. Go to 'Report Page'
2. Click on 'Schedule of The Day' form
3. See error

**Screenshots or Video**
![1689646935622](https://github.com/Haidoe/arc/assets/88930141/3b875f30-3ea6-428d-92b8-4dd7522587c7)

**Expected behavior:  ❗️**
Show '0' in the fields

**Actual behavior:  ❗️**
Blank fields

**Possible Solution:**
If you have any ideas or suggestions on how to fix the bug, please mention them here.

**Environment:**
- Device & Operating System:
- Browser and Version(if applicable):
- Jira Ticket(if applicable):
- Any other relevant information about your environment.

**Additional context:**

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by jaas666** [comment]
Fix included in #148

**Comment by jbsinluenam** [comment]
This is fixed.
