### ISSUE TITLE
no closing button on modal

### ISSUE THREAD

**Issue by wakapix** [Haidoe/arc#135]
## Bug Report

**Reporter: ❗️**
 @wakapix 

**Describe the bug: ❗️**
There is no closing button on modal.

**Steps to reproduce: ❗️**
1. Go to 'Production Report'
2. Click on '.any form'
3. See modal

**Screenshots or Video**
<img width="1132" alt="Screen Shot 2023-07-17 at 10 38 07 PM" src="https://github.com/Haidoe/arc/assets/99109622/69a936dd-5d97-4dd7-a857-230ab67c47a9">

**Expected behavior:  ❗️**
Arrow is supposed to be changed to "×" button, and user can close the modal by clicking the "×" button.

**Actual behavior:  ❗️**
The only way to close the modal is clicking outside of modal.

**Possible Solution:**
Arrow is supposed to be changed to "×" button, and user can close the modal by clicking the "×" button.

**Additional context:**

**Follow up checklist:  ❗️**
- [x]  Add Assignee
- [x]  Label priority ( priority-low, priority-medium, priority-high )
- [x]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by ksdhir** [comment]
@StephanyJade cannot find which issue is this duplicate of. Removing the tag and working on it.

**Comment by ksdhir** [comment]
This was fixed under https://github.com/Haidoe/arc/commit/bc820d222b15c00908924b19cd717bcc47c66c45 and https://github.com/Haidoe/arc/commit/bc820d222b15c00908924b19cd717bcc47c66c45

@wakapix Please do test it and verify.

**Comment by wakapix** [comment]
@ksdhir It's fixed, Thank you!
