### ISSUE TITLE
The design of the sidebar 

### ISSUE THREAD

**Issue by wakapix** [Haidoe/arc#136]
## Bug Report

**Reporter: ❗️**
 @wakapix 

**Describe the bug: ❗️**
The design of the sidebar confuses users that it is editable.

**Steps to reproduce: ❗️**
1. Go to 'Dashboard'
2. See error

**Screenshots or Video**
<img width="687" alt="Screen Shot 2023-07-17 at 10 44 37 PM" src="https://github.com/Haidoe/arc/assets/99109622/1c91dd1e-277d-42e1-ad77-dbc591cccd32">

**Expected behavior:  ❗️**
To change the information of project, user needs to click "edit" button.

**Possible Solution:**
Make these texts without underlining on a white background the same as other texts

**Follow up checklist:  ❗️**
- [x]  Add Assignee
- [x]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
This needs to be finalized by the design team before proceeding on my end.

CC: @StephanyJade

**Comment by Haidoe** [comment]
remove date bg

**Comment by Haidoe** [comment]
remove the edit btn

**Comment by rafaelajung** [comment]
@Haidoe 

just show the date as normal text, like other parts of the side bar. 
Please maintain the edit button.

**Comment by Haidoe** [comment]
Resolved.
