### ISSUE TITLE
Input form for date information

### ISSUE THREAD

**Issue by wakapix** [Haidoe/arc#137]
## Bug Report

**Reporter: ❗️**
 @wakapix 

**Describe the bug: ❗️**
When trying to enter date information, it's not clear that user needs to enter AM / PM

**Steps to reproduce: ❗️**
1. Go to 'Dashboard'
2. Click on 'Form'
3. See error

**Screenshots or Video**
<img width="843" alt="Screen Shot 2023-07-17 at 10 56 11 PM" src="https://github.com/Haidoe/arc/assets/99109622/d05254d0-998d-4b43-824b-7769b84a09f1">

**Possible Solution:**
Users can select AM or PM in the pull-down menu.

**Additional context:**

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by jbsinluenam** [comment]
I propose we use 24hr system.

**Comment by StephanyJade** [comment]
@jbsinluenam we are ok with the change. Just consider that this might affect the resto of the forms that contain time input fields.
Thank you!

**Comment by Haidoe** [comment]
Let's proceed with 24hr system then.

CC: @jbsinluenam  @StephanyJade

**Comment by Haidoe** [comment]
Will not proceed with this approach
