### ISSUE TITLE
style: Ubuntu font has jagged sharp edges

### ISSUE THREAD

**Issue by jbsinluenam** [Haidoe/arc#138]
## Bug Report

**Reporter: ❗️**
 @jbsinluenam 

**Describe the bug: ❗️**
ubuntu font has jagged sharp edges when display in small size

**Steps to reproduce: ❗️**
1. Go to 'Any page'
2. See error

**Screenshots or Video**
![1689659952711](https://github.com/Haidoe/arc/assets/88930141/266f0209-dead-4365-b9fa-88701b2aa86c)

**Expected behavior:  ❗️**
smooth edge font

**Environment:**
- Windows 11/ Chrome

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
Explore tailwind fixes: font smoothing
