### ISSUE TITLE
Arrow icons should be upside down

### ISSUE THREAD

**Issue by wakapix** [Haidoe/arc#139]
## Bug Report

**Reporter: ❗️**
 @wakapix 

**Describe the bug: ❗️**
Arrow icons to open and close forms should be upside down

**Steps to reproduce: ❗️**
1. Go to 'Dashboard'
2. See error

**Screenshots or Video**
<img width="1035" alt="Screen Shot 2023-07-17 at 11 07 49 PM" src="https://github.com/Haidoe/arc/assets/99109622/a0096e8c-1973-438e-9108-30ef3d12a75c">

**Expected behavior:  ❗️**
Usually arrow icons should be upside down

**Follow up checklist:  ❗️**
- [x]  Add Assignee
- [x]  Label priority ( priority-low, priority-medium, priority-high )
- [x]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by ksdhir** [comment]
@wakapix 
Closing this as it was pretty small issue.
