### ISSUE TITLE
Suggestion: Add option to access app through login button

### ISSUE THREAD

**Issue by rafaelajung** [Haidoe/arc#141]
## Bug Report

**Reporter: ❗️**
 @rjung07 

**Describe the bug: ❗️**
Not exactly a bug, but I would add an option to access the app through login for a view-only option, if possible. Or redirect to sign in with Google.

**Steps to reproduce: ❗️**
1. Go to Arc 'Sign In' page
2. Click on 'login' button

**Screenshots or Video**
Not applicable

**Expected behavior:  ❗️**
When clicking this button some message could be showed or redirect to a different sign in option.

**Actual behavior:  ❗️**
When clicking this button nothing happens. I understand it was not supposed to, but this is a suggestion.

**Possible Solution:**
Redirect user to Google login.

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
There are a lot of conflicts to implement this feature. 
will not implement this.

CC: @rjung07 @StephanyJade
