### ISSUE TITLE
Sign In Style: Add style to Google authentication

### ISSUE THREAD

**Issue by rafaelajung** [Haidoe/arc#142]
## Bug Report

**Reporter: ❗️**
 @rjung07 

**Describe the bug: ❗️**
The modal/pop up for Google Sign in is aligned to the left and description 'kaos-project-2' could be deleted.

**Steps to reproduce: ❗️**
1. Go to Sign in page
2. Click on 'Sign in with Google'

**Screenshots or Video**
![image](https://github.com/Haidoe/arc/assets/123789857/0a2ff9e1-9363-4558-a30a-0e7ae50c8c5d)

**Expected behavior:  ❗️**
A centralized or styled page with Google login. 

**Actual behavior:  ❗️**
Is just showing one pop-up window.

**Possible Solution:**
![image](https://github.com/Haidoe/arc/assets/123789857/5b065c74-c37b-4fe7-b746-361515ed2ab1)

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by StephanyJade** [comment]
@Haidoe.
Cc: @rjung07 

Haids, please let me know if this is doable during this stage. In the mean time I'll tag this ticket with the won’t do label.

Thank you!

**Comment by Haidoe** [comment]
Hi @rjung07 

We don't have this access to implement this because we are using 3rd party to handle the auth.

CC: @StephanyJade
