### ISSUE TITLE
Menu Style: Add hover state for navigation menu links

### ISSUE THREAD

**Issue by rafaelajung** [Haidoe/arc#143]
## Bug Report

**Reporter: ❗️**
 @rjung07 

**Describe the bug: ❗️**
Link on the navigation menu is missing a hover state, which makes it confusing to see if they are clickable. Hover state is the same as active state.

**Steps to reproduce: ❗️**
1. Go to 'Production Page'
2. Hover on navigation menu

**Screenshots or Video**
![image](https://github.com/Haidoe/arc/assets/123789857/e7816c84-bd82-420e-a2bf-c27595c4ad90)

**Expected behavior:  ❗️**
Design a different hover state for navigation links.

**Actual behavior:  ❗️**
Hover state for navigation links is the same as the active one.

**Possible Solution:**
Create a purple or different grey hover state.

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by StephanyJade** [comment]
@Haidoe and @rjung07 

Assuming we will be changing for both design and development, I'll assign the two of you to this ticket.

Thank you.

**Comment by ksdhir** [comment]
@rjung07 Once you decide on the solution, let me know.

**Comment by rafaelajung** [comment]
@Haidoe @ksdhir and @jbsinluenam 

**Make the link bold while hovering.**

**Comment by ksdhir** [comment]
@rjung07 please check.
