### ISSUE TITLE
Production Suggestion: Make no production page and list of productions more consistant

### ISSUE THREAD

**Issue by rafaelajung** [Haidoe/arc#145]
## Bug Report

**Reporter: ❗️**
 @rjung07 

**Describe the bug: ❗️**
On production page, the style and layout change when there is no production and when there is a list. On mockup did not annoy me, but on the flow, it feels a little off.

**Steps to reproduce: ❗️**
1. Go to 'Production'
2. Click on 'New Production'
3. See the difference between pages

**Screenshots or Video**
![image](https://github.com/Haidoe/arc/assets/123789857/9f47d4a4-e6f0-447c-88db-f97fc3186961)

**Expected behavior:  ❗️**
A layout that doesn't change much and doesn't move much.

**Actual behavior:  ❗️**
A layout that changes a little and gives the user a weird sensation that something changed.

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by jbsinluenam** [comment]
Are designers going to finalize the mock-up first?

**Comment by Haidoe** [comment]
resolved through the discussion
