### ISSUE TITLE
Production Report UX: Missing a save cue/sign on editing the forms

### ISSUE THREAD

**Issue by rafaelajung** [Haidoe/arc#146]
## Bug Report

**Reporter: ❗️**
 @rjung07 

**Describe the bug: ❗️**
While adding information to the forms, is weird for the user to save automatically and just clicking on the outside.

**Steps to reproduce: ❗️**
1. Go to 'Production'
2. Click on 'Schedule of the day'
3. Edit times
4. Click outside modal

**Screenshots or Video**
![image](https://github.com/Haidoe/arc/assets/123789857/16114167-dd0a-4b8f-9c59-18ceb2c05842)

**Expected behavior:  ❗️**
A clear sign that things have been saved.

**Actual behavior:  ❗️**
Just a change that saves authomatically.

**Follow up checklist:  ❗️**
- [x]  Add Assignee
- [x]  Label priority ( priority-low, priority-medium, priority-high )
- [x]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
Will create this one,

Add two buttons throughout all the report forms: cancel and save

- make the save primary
-  make cancel the secondary

**Comment by rafaelajung** [comment]
Here is an example.

![image](https://github.com/Haidoe/arc/assets/123789857/16de0aad-598c-4255-8dff-58a52ec5a32b)

Maintain the right padding 16px and bottom padding 24px. I suggest the buttons are something around 88x40 px and 24px spacing between them.

**Comment by ksdhir** [comment]
@rjung07 Thanks Hafa!

**Comment by ksdhir** [comment]
@rjung07 I think instead of delete we have cancel here.

**Comment by ksdhir** [comment]
@rjung07 Please verify.
