### ISSUE TITLE
Production Report Form: Allow user to save and exit by hitting enter key

### ISSUE THREAD

**Issue by rafaelajung** [Haidoe/arc#147]
## Bug Report

**Reporter: ❗️**
 @rjung07 

**Describe the bug: ❗️**
Once finished adding information to forms, user should be able to exit by using keyboard.

**Steps to reproduce: ❗️**
1. Go to 'Production Report'
2. Click on any form
3. Edit information

**Screenshots or Video**
-

**Expected behavior:  ❗️**
Be able to exit the edited form by using the keyboard.

**Actual behavior:  ❗️**
No keyboard command allows the user to exit the editable form.

**Possible Solution:**
For accessibility, it's also recommended to allow user to navigate with keyboard.

**Follow up checklist:  ❗️**
- [x]  Add Assignee
- [x]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by StephanyJade** [comment]
@Haidoe 

Please consider this accessibility fixing and let me know if it's doable in this stage.

Thank you.

**Comment by Haidoe** [comment]
Hi @StephanyJade 

I am going to implement every time the user hit "esc" key it will trigger closing of modal.

Let me know if this will suffice the requirement.

**Comment by Haidoe** [comment]
This is partially implemented by @ksdhir .

CC: @StephanyJade @rjung07
