### ISSUE TITLE
Production Report Modal: Modals in edit view should not collapse

### ISSUE THREAD

**Issue by rafaelajung** [Haidoe/arc#149]
## Bug Report

**Reporter: ❗️**
 @rjung07 

**Describe the bug: ❗️**
Modal is collapsing on the full-size view. Deactivate the arrows to expand and collapse for the form editing option.

**Steps to reproduce: ❗️**
1. Go to 'Production Report'
2. Click on any form
3. Hit 'shift' or 'command' + 'enter'

**Screenshots or Video**
![image](https://github.com/Haidoe/arc/assets/123789857/433d2669-ca00-4d44-b09f-c84d98a06404)

**Expected behavior:  ❗️**
Maintain view always expanded.

**Actual behavior:  ❗️**
While using keyboard navigation, modal collapses.

**Follow up checklist:  ❗️**
- [x]  Add Assignee
- [x]  Label priority ( priority-low, priority-medium, priority-high )
- [x]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by StephanyJade** [comment]
@Haidoe @rjung07 

The correct behaviour will be changing the down arrow for an X icon so the user know that can close the form by clicking there.

Thank you.

**Comment by Haidoe** [comment]
Please take note Jade's comment, @jbsinluenam

**Comment by ksdhir** [comment]
> @Haidoe @rjung07
> 
> The correct behaviour will be changing the down arrow for an X icon so the user know that can close the form by clicking there.
> 
> Thank you.

@StephanyJade Thanks Jade for mentioning that. This will be dealt / handled separately in the issue https://github.com/Haidoe/arc/issues/135

**Comment by ksdhir** [comment]
@StephanyJade 
Pressing just space also does that to the accordion. Since our accordion is not accordion anymore on Desktop (as of now) i'll completely remove the toggle.

@jbsinluenam @Haidoe 
Culprit:
![Screenshot 2023-07-21 at 2 52 14 PM](https://github.com/Haidoe/arc/assets/44022086/257f4f7b-f3cc-429a-af77-b072ea4fb658)

**Comment by ksdhir** [comment]
Fixed the issue.
@rjung07 Please verify.
