### ISSUE TITLE
Production Report Forms: Have some required fields to avoid creating blank rows

### ISSUE THREAD

**Issue by rafaelajung** [Haidoe/arc#150]
## Bug Report

**Reporter: ❗️**
 @rjung07 

**Describe the bug: ❗️**
While creating new rows on 'scenes shot form' only allow user to add them once required fields have been added.

**Steps to reproduce: ❗️**
1. Go to 'Production Report'
2. Click on 'Scenes Shot form'
3. Click in 'Create new line'
4. See blank line created

**Screenshots or Video**
![image](https://github.com/Haidoe/arc/assets/123789857/aeacd603-6175-4df3-8704-5cf539903a32)

**Expected behavior:  ❗️**
A row with information added and filled.

**Actual behavior:  ❗️**
An empty row.

**Follow up checklist:  ❗️**
- [x]  Add Assignee
- [x]  Label priority ( priority-low, priority-medium, priority-high )
- [x]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by ksdhir** [comment]
@rjung07 The issue has been fixed. Please verify.

**Comment by rafaelajung** [comment]
Yes, is ok and correct now.
