### ISSUE TITLE
Production Nav: When going back to productions, report and dashboard should be active

### ISSUE THREAD

**Issue by rafaelajung** [Haidoe/arc#151]
## Bug Report

**Reporter: ❗️**
 @rjung07 

**Describe the bug: ❗️**
Once the user has already created the productions while going back to the productions page, the navigation menu should allow them to navigate through the production report and dashboard.

**Steps to reproduce: ❗️**
1. Go to 'Production Report'
2. Click on 'Production' on the navigation menu
3. Try to click production report and dashboard again

**Screenshots or Video**
-

**Expected behavior:  ❗️**
When going back to production page, user should be able to use the navigation menu and click production report and dashboard.

**Actual behavior:  ❗️**
The links for production report and dashboard are greyed out.

**Follow up checklist:  ❗️**
- [x]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [x]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
Hi @rjung07 

I remembered that we had a discussion about this and agreed to disable the navigation going to the report and dashboard once the user is on the homepage(w/ production list)

**Comment by Haidoe** [comment]
CC: @StephanyJade
