### ISSUE TITLE
Report page: inconsistent color of divider in report page

### ISSUE THREAD

**Issue by jbsinluenam** [Haidoe/arc#152]
## Bug Report

**Reporter: ❗️**
 @jbsinluenam 

**Describe the bug: ❗️**
Now we have three colors.

**Steps to reproduce: ❗️**
1. Go to 'Report page'

**Screenshots or Video**
![1689664938839](https://github.com/Haidoe/arc/assets/88930141/35a5bfcb-8dd4-445a-9fd9-8d45bba8e623)

**Expected behavior:  ❗️**
One color.

**Actual behavior:  ❗️**
Three colors

**Possible Solution:**
I would propose we go for a light grey for  a clean UI.

**Follow up checklist:  ❗️**
- [x]  Add Assignee
- [x]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
Hi @rjung07 ,

Could you provide the final color of the following dividers.

**Comment by rafaelajung** [comment]
Hi @Haidoe, @jbsinluenam and @ksdhir,

please use **dark: "#565656",** on light background and **arc: "#FDFDFA"**, in purple and dark background.

Also, please use 1.5pts to the thickness of it.

**Comment by rafaelajung** [comment]
![image](https://github.com/Haidoe/arc/assets/123789857/a3c80054-8813-4653-80ab-906ca986cb70)

@jbsinluenam 

Light grey colour for line: #DADADA

**Comment by jbsinluenam** [comment]
Fixed.
