### ISSUE TITLE
Production Report Mobile: Missing forms and navigation menu

### ISSUE THREAD

**Issue by rafaelajung** [Haidoe/arc#153]
## Bug Report

**Reporter: ❗️**
 @rjung07 

**Describe the bug: ❗️**
When using the mobile app on responsive mode on the desktop, after signing in, creating new production and going to the production report, only the information bar is showing. Missing hamburger menu and other forms. On mobile, I cannot login and create new production (Kat already opened this issue).

**Steps to reproduce: ❗️**
1. Go to 'Add New Production'
2. Click on 'The Last of Us' production
3. Check report page

**Screenshots or Video**
![image](https://github.com/Haidoe/arc/assets/123789857/b8dc0022-5deb-412e-b7f4-32bec41d73fc)

**Expected behavior:  ❗️**
Show hamburger menu and the forms (even not styled responsively yet).

**Actual behavior:  ❗️**
Only information from the project is showing.

**Follow up checklist:  ❗️**
- [x]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [x]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
duplicate issue.

Resolved
