### ISSUE TITLE
Homepage - Multiple Dummy Production

### ISSUE THREAD

**Issue by Haidoe** [Haidoe/arc#154]
## Bug Report

**Reporter: ❗️**
 @Haidoe 

**Describe the bug: ❗️**
If you click the "New Production" CTA multiple times it will generate enormous amount of production data

**Steps to reproduce: ❗️**
1. Go to '/home'
2. Click on 'New Production' multiple times
3. Then refresh the page

**Screenshots or Video**

<img width="1331" alt="Screenshot 2023-07-18 at 12 47 35 AM" src="https://github.com/Haidoe/arc/assets/20655791/2eec01f0-6c1d-4a5c-af28-a33f512b7fbd">

**Expected behavior:  ❗️**
When I clicked the new productions, it should have a loading state.
- while in loading state, the button will be disabled

**Actual behavior:  ❗️**
No indicator of loading state and prone to create multiple new production when clicked multiple times

**Comment by Haidoe** [comment]
- New Production when clicked will display WIP Dialog

**Comment by StephanyJade** [comment]
Please add the **Create sample production CTA** and the message for the info message.

<img width="375" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/8ccf7f66-819d-486c-9206-b1a8f1db977a">

**Comment by jbsinluenam** [comment]
Fixed.
