### ISSUE TITLE
Production Report Forms

### ISSUE THREAD

**Issue by Haidoe** [Haidoe/arc#155]
## Bug Report

**Reporter: ❗️**
 @Haidoe 

**Describe the bug: ❗️**
Forms that are in a read-only state can be edited by navigating into it using the tab key.

**Steps to reproduce: ❗️**
1. Go to the report page
2. press the tab key at least 4 times until you reach input fields that are in a read-only state.
3. add an input

**Screenshots or Video**

<img width="1105" alt="Screenshot 2023-07-18 at 12 58 53 AM" src="https://github.com/Haidoe/arc/assets/20655791/be65bfab-bdaf-4ace-a546-082c95952493">

**Expected behavior:  ❗️**
Prevent navigating to input fields that are in a read-only state with a tab.

**Possible Solution:**
add negative tabindex to input fields

**Comment by jbsinluenam** [comment]
This is fixed.
