### ISSUE TITLE
Report Form -  Inconsistent Font Sizes, Weight, Colors

### ISSUE THREAD

**Issue by Haidoe** [Haidoe/arc#156]
## Bug Report

**Reporter: ❗️**
 @Haidoe 

**Describe the bug: ❗️**
Font sizes, weights, colors are inconsistent

**Steps to reproduce: ❗️**
Go to Production report page

**Screenshots or Video**
<img width="1118" alt="Screenshot 2023-07-18 at 1 16 20 AM" src="https://github.com/Haidoe/arc/assets/20655791/57f25259-ce43-48d6-8543-bf03e73f916b">

**Expected behavior:  ❗️**
Make it consistent refer to the Figma

**Comment by jbsinluenam** [comment]
This is from figma.
![1689794730156](https://github.com/Haidoe/arc/assets/88930141/a2a61f7c-659e-4577-bfa6-c57c402201a2)
