### ISSUE TITLE
Navigation Color

### ISSUE THREAD

**Issue by kbmirambel** [Haidoe/arc#161]
## Bug Report

**Reporter: ❗️**
 @kbmirambel 

**Describe the bug: ❗️**
Different color used on the navigation on the specific page

**Steps to reproduce: ❗️**
1. Once you are logged In, you'll see the active links on the top navigation

**Screenshots or Video**
<img width="572" alt="Screen Shot 2023-07-18 at 3 22 22 PM" src="https://github.com/Haidoe/arc/assets/123606372/52eb8bd2-0f35-48ea-9ec2-e39d32d2ad64">

**Expected behavior:  ❗️**
The color should be - rgba(241, 104, 137, 1)

**Actual behavior:  ❗️**
The color is currently - rgba(255, 132, 161, 1) which is the hover state color

**Environment:**
- Web

**Follow up checklist:  ❗️**
- [x]  Add Assignee
- [x]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by ksdhir** [comment]
Updated the styles as per the requirement.
@kbmirambel Please verify.
