### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by kbmirambel** [Haidoe/arc#163]
## Bug Report

**Reporter: ❗️**
 @kbmirambel 

**Describe the bug: ❗️**
The title "Your productions" is center aligned

**Screenshots or Video**
<img width="527" alt="Screen Shot 2023-07-18 at 6 06 27 PM" src="https://github.com/Haidoe/arc/assets/123606372/c7af722f-a9e4-4700-b84e-9c98453c5bfe">

**Expected behavior:  ❗️**
Title should be left aligned

**Actual behavior:  ❗️**
It's currently centered

**Additional context:**

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by jbsinluenam** [comment]
If I left align this one- it will not continue with the prior screen which is center align.

**Comment by Haidoe** [comment]
As discussed:

The Text will be inside.

CC:  @StephanyJade , @rjung07  @jbsinluenam

**Comment by Haidoe** [comment]
you will use contrast-base

**Comment by jbsinluenam** [comment]
Lastest update, no bg. change color to contrast-dark

**Comment by jbsinluenam** [comment]
This is fixed.
