### ISSUE TITLE
Button Styles

### ISSUE THREAD

**Issue by kbmirambel** [Haidoe/arc#164]
## Bug Report

**Reporter: ❗️**
 @kbmirambel 

** Describe the bug: ❗️**
The button already has drop shadow 

**Screenshots or Video**
<img width="238" alt="Screen Shot 2023-07-18 at 6 36 43 PM" src="https://github.com/Haidoe/arc/assets/123606372/2b3ff554-5075-4601-981e-f1e955f9ab9d">

**Expected behavior:  ❗️**
Button doesn't have any shadows

**Additional context:**

**Follow up checklist:  ❗️**
- [x]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [x]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by StephanyJade** [comment]
@Haidoe 

Please let me know if this worth considering. In the meantime I'll add the wont do tag.

Thank you.
