### ISSUE TITLE
Production Page: Schedule of the day - Missing Time

### ISSUE THREAD

**Issue by kbmirambel** [Haidoe/arc#165]
## Bug Report

**Reporter: ❗️**
 @kbmirambel 

**Describe the bug: ❗️**
Missing Time for "schedule of the day"

**Steps to reproduce: ❗️**
1. Go to "Production report" Page

**Screenshots or Video**
<img width="990" alt="production page-1" src="https://github.com/Haidoe/arc/assets/123606372/2863e9d6-4013-4400-a3cd-3a16feb696db">

**Expected behavior:  ❗️**
Visible time

**Actual behavior:  ❗️**
Missing time

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by jbsinluenam** [comment]
I implement it like this for now, because I feel like there's no point to make it as an input. We can discuss tomorrow.
![1689978309301](https://github.com/Haidoe/arc/assets/88930141/ae878266-19ba-4c49-805e-cd5437854adc)
