### ISSUE TITLE
Production Report : Actual Schedule

### ISSUE THREAD

**Issue by kbmirambel** [Haidoe/arc#166]
## Bug Report

**Reporter: ❗️**
 @kbmirambel 

**Describe the bug: ❗️**
Missing Line before total for actual schedule

**Screenshots or Video**
<img width="504" alt="Screen Shot 2023-07-18 at 6 56 25 PM" src="https://github.com/Haidoe/arc/assets/123606372/226cd869-9052-4e56-ad19-994358b60395">

**Expected behavior:  ❗️**
Blank separation to the total

**Actual behavior:  ❗️**
Underline should be visible

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by jbsinluenam** [comment]
This is fixed.
