### ISSUE TITLE
Production Page: Rolls

### ISSUE THREAD

**Issue by kbmirambel** [Haidoe/arc#167]
## Bug Report

**Reporter: ❗️**
 @kbmirambel 

**Describe the bug: ❗️**
Missing lines every row

**Screenshots or Video**
<img width="522" alt="Screen Shot 2023-07-18 at 7 02 43 PM" src="https://github.com/Haidoe/arc/assets/123606372/9e44e56c-06cc-4cef-9c21-a191f548cfce">

**Expected behavior:  ❗️**
Visible line every other row

**Actual behavior:  ❗️**
no lines visible

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by jbsinluenam** [comment]
This one I feel like we dont need a divider here. It will only added clutter.

**Comment by Haidoe** [comment]
As discussed, we are going to use lines to separate rows.

@rjung07 will provide the subtle gray code before @jbsinluenam  will work on this issue.

**Comment by rafaelajung** [comment]
@Haidoe and @jbsinluenam 

the grey colour of the lines dividing rows is #DADADA
![Uploading image.png…]()

**Comment by jbsinluenam** [comment]
This is fixed.
