### ISSUE TITLE
Production Report : Cast Time Log

### ISSUE THREAD

**Issue by kbmirambel** [Haidoe/arc#168]
## Bug Report

**Reporter: ❗️**
 @kbmirambel 

**Describe the bug: ❗️**
More padding on the buttons and color doesn't match

**Screenshots or Video**
<img width="1041" alt="Screen Shot 2023-07-18 at 7 11 16 PM" src="https://github.com/Haidoe/arc/assets/123606372/0425c988-f287-4436-b512-c8d968b71e2f">

**Expected behavior:  ❗️**
More padding inside the padding and color should be - rgba(106, 106, 198, 1)
Mock up:
<img width="155" alt="Screen Shot 2023-07-18 at 7 14 53 PM" src="https://github.com/Haidoe/arc/assets/123606372/0d87f5d4-7de9-484d-93ed-8eff7222ca62">

**Actual behavior:  ❗️**
less padding

**Follow up checklist:  ❗️**
- [x]  Add Assignee
- [x]  Label priority ( priority-low, priority-medium, priority-high )
- [x]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by ksdhir** [comment]
@kbmirambel 
Updated all the" Create New Line" buttons as in Figma. Updated the color and padding.
Please verify.
