### ISSUE TITLE
Dashboard-Progress logic

### ISSUE THREAD

**Issue by jbsinluenam** [Haidoe/arc#231]
## Bug Report

**Reporter: ❗️**
 @jbsinluenam 

**Describe the bug: ❗️**
The logic is not correct.

**Screenshots or Video**
![Screenshot 2023-07-29 141325](https://github.com/Haidoe/arc/assets/88930141/b6e425c3-3cde-4b79-8915-932a810fd5e3)

Here's the explanation.

Every day during shooting, the crew must be paid for a minimum of 12 hours, regardless of whether they work less than that. Only the hours that go beyond 12 hours will be counted, and these extra hours will be accumulated for tracking the production progress.

I recommend the following color-coded scheme for tracking progress:

100% to 110% = Green
111% to 125% = Yellow
Over 126% = Red
* If you go slightly over the time, up to 110%, it is considered normal for production.
** Normally they will calculate this based on Actual Hours, but I'll leave that to you. 

Here's the suggested calculation method

Exhibit 1:
Let's consider a shooting schedule of 10 days, and we are currently on the 5th day.

Total hours for the entire shooting schedule = 12 hours/day * 10 days = 120 hours.

Total hours worked until the 5th day = 12 hours/day * 5 days = 60 hours.

Breakdown of hours worked each day:

1st day: 10 hours = 12 hours (base hours)
2nd day: 12 hours = 12 hours (base hours)
3rd day: 15 hours = 15 hours (includes 3 extra hours)
4th day: 12 hours = 12 hours (base hours)
5th day: 10 hours = 12 hours (base hours)
Actual total hours worked = 63 hours.
Base number of hours = 60 hours.

Production progress: 63/60 = 1.05 (approximately) = Green.

Please note that going slightly over the base hours up to 110% is still considered normal for production, as represented by the "Green" status in this example.

-----------------------------------------------------------------------------------------------------------------------------------------------

Exhibit 2:
Total days of shooting: 30 days
Currently on the 25th day.

Total hours for the entire shooting schedule = 12 hours/day * 30 days = 360 hours.

Total hours worked until the 25th day = 12 hours/day * 25 days = 300 hours.

Breakdown of hours worked each day:

1st day: 10 hours = 12 hours (base hours)
2nd day: 14 hours = 14 hours (includes 2 extra hours)
3rd day: 13 hours = 13 hours (includes 1 extra hour)
4th day: 12 hours = 12 hours (base hours)
5th day: 11 hours = 12 hours (base hours)
6th day: 12 hours = 12 hours (base hours)
7th day: 12 hours = 12 hours (base hours)
8th day: 14 hours = 14 hours (includes 2 extra hours)
9th day: 15 hours = 15 hours (includes 3 extra hours)
10th day: 13 hours = 13 hours (includes 1 extra hour)
11th day: 12 hours = 12 hours (base hours)
12th day: 13 hours = 13 hours (includes 1 extra hour)
13th day: 14 hours = 14 hours (includes 2 extra hours)
14th day: 15 hours = 15 hours (includes 3 extra hours)
15th day: 13 hours = 13 hours (includes 1 extra hour)
16th day: 14 hours = 14 hours (includes 2 extra hours)
17th day: 12 hours = 12 hours (base hours)
18th day: 13 hours = 13 hours (includes 1 extra hour)
19th day: 12 hours = 12 hours (base hours)
20th day: 14 hours = 14 hours (includes 2 extra hours)
21st day: 15 hours = 15 hours (includes 3 extra hours)
22nd day: 16 hours = 16 hours (includes 4 extra hours)
23rd day: 17 hours = 17 hours (includes 5 extra hours)
24th day: 14 hours = 14 hours (includes 2 extra hours)
25th day: 18 hours = 18 hours (includes 6 extra hours)
Accumulated extra hours: 43 hours (from the 2nd, 3rd, 8th, 9th, 12th, 13th, 14th, 16th, 20th, 21st, 22nd, and 25th day).

Actual total hours worked (including accumulated extra hours) = 300 + 43 = 343 hours.

Base number of hours = 300 hours.

Production progress: 343/300 ≈ 1.14 = Yellow.

In this exhibit, the production progress is approximately 1.14, which falls under the "Yellow" status as it's within the 111% to 125% range.

------------------------------------------------------------------------------------------------------------------------------------------------

Exhibit 3:
Total days of shooting: 30 days
On 26th-27th day, actor is sick so we cant have shooting for two days.

Currently on the 28th day.

Total hours for the entire shooting schedule = 12 hours/day * 30 days = 360 hours.

Total hours worked until the 28th day = 12 hours/day * 28 days = 336 hours.

Breakdown of hours worked each day:

1st day: 10 hours = 12 hours (base hours)
2nd day: 12 hours = 12 hours (base hours)
3rd day: 15 hours = 15 hours (includes 3 extra hours)
4th day: 16 hours = 16 hours (includes 4 extra hours)
5th day: 14 hours = 14 hours (includes 2 extra hours)
6th day: 12 hours = 12 hours (base hours)
7th day: 11 hours = 12 hours (base hours)
8th day: 12 hours = 12 hours (base hours)
9th day: 13 hours = 13 hours (includes 1 extra hour)
10th day: 15 hours = 15 hours (includes 3 extra hours)
11th day: 12 hours = 12 hours (base hours)
12th day: 13 hours = 13 hours (includes 1 extra hour)
13th day: 14 hours = 14 hours (includes 2 extra hours)
14th day: 15 hours = 15 hours (includes 3 extra hours)
15th day: 13 hours = 13 hours (includes 1 extra hour)
16th day: 14 hours = 14 hours (includes 2 extra hours)
17th day: 12 hours = 12 hours (base hours)
18th day: 13 hours = 13 hours (includes 1 extra hour)
19th day: 12 hours = 12 hours (base hours)
20th day: 14 hours = 14 hours (includes 2 extra hours)
21st day: 15 hours = 15 hours (includes 3 extra hours)
22nd day: 16 hours = 16 hours (includes 4 extra hours)
23rd day: 17 hours = 17 hours (includes 5 extra hours)
24th day: 14 hours = 14 hours (includes 2 extra hours)
25th day: 18 hours = 18 hours (includes 6 extra hours)
26th day: NO SHOOTING (Actor sick - counted as 12 hours)
27th day: NO SHOOTING (Actor sick - counted as 12 hours)
28th day: 20 hours = 20 hours (includes 8 extra hours)
Accumulated extra hours: 68 hours (from the 3rd, 4th, 5th, 9th, 10th, 13th, 14th, 16th, 20th, 21st, 22nd, 25th, and 28th day).

Actual total hours worked (including accumulated extra hours and time for no shooting days): 336 + 68 + 24 = 428 hours.

Base number of hours = 336 hours.

Production progress: 428/336 ≈ 1.27 = Red.

In this exhibit, the production progress is approximately 1.27, which falls under the "Red" status as it's over 126%. The two days with no shooting (due to actors being sick) are still counted as 12 hours each, contributing to the overall production progress even though no actual shooting occurred on those days.

**Comment by jbsinluenam** [comment]
The production progress chart, even though named as "progress," actually represents how efficiently the producer manages the production to complete the project. The goal is to finish the production within a set timeframe and without exceeding the expected resource allocation (budget).

Instead of explicitly mentioning the budget, the chart serves as a tool to inform the executives or stakeholders about the overall efficiency of the production process. It provides a clear indication of the project's advancement at any given point.

For instance, if the chart shows that the production progress is at 50%, it means the team has reached the midpoint of the scheduled shooting period. Additionally, the color-coded system (Green, Yellow, Red) demonstrates the daily performance in terms of time management. When the average daily progress remains within the 100% to 110% range (Green), it indicates that the production is running smoothly and efficiently, meeting the expected shooting schedule. This reassures the executives that, on average, each day is being utilized well to maintain a reasonable pace toward completing the project on time.

By presenting the production progress in this manner, it enables the executives to have a clear understanding of the production's overall status without explicitly discussing budget details, providing them with valuable insights to make informed decisions and adjustments if needed.


### The production progress chart serves as a distinctive feature that sets us apart from our competitors. 

Our production progress chart automates and streamlines the process, setting us apart from competitors who rely on manual handling of 30 days of Excel sheets for calculations. With our chart, valuable time and effort are saved, as it offers easily interpretable visual data, providing quick insights into the production process's overall efficiency without the need for extensive Excel analysis.

Unlike many competitors, the chart acts as a visual guide, clearly indicating the overall efficiency of the production process. It allows executives to understand the project's status easily and make informed decisions without the need for complex budget discussions.

**Comment by Haidoe** [comment]
Finally!!!!!!!
