### ISSUE TITLE
Tablet size: Navbar is missing. Unable to scroll.

### ISSUE THREAD

**Issue by jbsinluenam** [Haidoe/arc#236]
## Bug Report

**Reporter: ❗️**
 @jbsinluenam 

**Describe the bug: ❗️**
In tablet size, Navbar is missing and it is unscrollable.

**Steps to reproduce: ❗️**
1. Use Inspector and set your browser size to tablet size

**Screenshots or Video**
![1690684801520](https://github.com/Haidoe/arc/assets/88930141/f42d453a-b850-46b6-a93b-53114d56e8cd)
![1690684819496](https://github.com/Haidoe/arc/assets/88930141/30ef6e47-420f-4598-8b65-82672123554b)

**Expected behavior:  ❗️**
Navbar at the bottom, and it should be scrollable.

**Comment by Haidoe** [comment]
can't replicate
