### ISSUE TITLE
Landing page - nav menu

### ISSUE THREAD

**Issue by StephanyJade** [Haidoe/arc#246]
## Bug Report

**Reporter: ❗️**
 @StephanyJade 

**Describe the bug: ❗️**
The navigation menu should take the users so each section of the landing page.

**Steps to reproduce: ❗️**
1. Go to Landing page
2. Click on options in the nav menu and try to navigate.

**Screenshots or Video**
![image](https://github.com/Haidoe/arc/assets/128421316/9fae6034-2d48-4b2d-b68a-7cf4271caefc)

**Expected behavior:  ❗️**
Take the users to each related section.

**Actual behavior:  ❗️**
Nothing happens. Buttons inactive but with active status.

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by ksdhir** [comment]
Fixed and closing
