### ISSUE TITLE
Report page - Forms in mobile screens.

### ISSUE THREAD

**Issue by StephanyJade** [Haidoe/arc#249]
## Bug Report

**Reporter: ❗️**
 @StephanyJade 

**Describe the bug: ❗️**
Time info hidded in mobile view

**Steps to reproduce: ❗️**
1. Go to report page and try to fill the forms in resolutions under 415px

**Screenshots or Video**
![image](https://github.com/Haidoe/arc/assets/128421316/99908e85-944e-4149-8498-b25fb9c670db)

**Expected behavior:  ❗️**
Visible information in the forms.

**Actual behavior:  ❗️**
The PM and AM info is being hidded.

**Environment:**
- Device & Operating System:
- Browser and Version(if applicable): Chrome - Inspect Iphone 12 pro

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
@jbsinluenam 

Time will be completely removed.

CC: @StephanyJade
