### ISSUE TITLE
Report page - Extras Cast Forms icons

### ISSUE THREAD

**Issue by StephanyJade** [Haidoe/arc#252]
Reporter: ❗️
@StephanyJade

Describe the bug: ❗️
In mobile view, when seeing the Not Shot Form, the icons to delete and edit are too small. For accesibility, the icons mus be at least 24x24px

Screenshots or Video
![image](https://github.com/Haidoe/arc/assets/128421316/89f629e0-688b-4124-ad4f-81f3f4e8f519)

Expected behavior: ❗️
Increase the size to 24x24px

Actual behavior: ❗️
Icons in 12x12px

Additional context:

Follow up checklist: ❗️

 Add Assignee
 Label priority ( priority-low, priority-medium, priority-high )
 Label Milestone ( Alpha, Beta )
 Label Issue Type ( Style, Code, API )

**Comment by ksdhir** [comment]
Fixed and closing
