### ISSUE TITLE
Dashboard - Enhancement

### ISSUE THREAD

**Issue by StephanyJade** [Haidoe/arc#255]
## Bug Report

**Reporter: ❗️**
 @StephanyJade 

**Describe the bug: ❗️**
The dashboard looks a little off, we can propose something else if we have time (The design is not so attractive).

**Screenshots or Video**
![image](https://github.com/Haidoe/arc/assets/128421316/39b6fc57-fe47-40be-ac75-1542515d5e04)

**Possible Solution:**
Reference to a better design:
<img width="783" alt="image" src="https://github.com/Haidoe/arc/assets/128421316/f5b21cce-fa8f-4e2c-82b9-42b86ed481ed">

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
Too late to implement redesign. 

CC: @StephanyJade and @rjung07
