### ISSUE TITLE
Download Report button does nothing.

### ISSUE THREAD

**Issue by ksdhir** [Haidoe/arc#261]
## Bug Report

**Reporter: ❗️**
 @ksdhir

**Describe the bug: ❗️**
The Download Report button on dashboard does nothing.

**Steps to reproduce: ❗️**
1. Go to 'dashboard' of any production
2. Scroll down to 'the bottom of the page'
3. Click on 'Dashboard Report' button.
4. Nothing appears

**Screenshots or Video**
![Screenshot 2023-07-31 at 12 12 21 PM](https://github.com/Haidoe/arc/assets/44022086/370e13cb-fcff-48a5-99ef-d49f7482cc8c)

**Expected behavior:  ❗️**
The button should download the report or display a message or modal that this is a future feature.

**Actual behavior:  ❗️**
The button does nothign on click.

**Possible Solution:**
The future feature component could be used here.

**Follow up checklist:  ❗️**
- [x]  Add Assignee
- [x]  Label priority ( priority-low, priority-medium, priority-high )
- [x]  Label Milestone ( Alpha, Beta  )
- [x]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
issue resolved

https://github.com/Haidoe/arc/issues/253
