### ISSUE TITLE
Report & Dashboard Page - Section Header Radius

### ISSUE THREAD

**Issue by Haidoe** [Haidoe/arc#263]
## Bug Report

**Reporter: ❗️**
 @Haidoe 
 
**Steps to reproduce: ❗️**
1. Go to Report and Desktop Page

**Screenshots or Video**
![Screenshot 2023-07-31 at 12 22 01 PM](https://github.com/Haidoe/arc/assets/20655791/66ab79dd-d46b-462b-8518-afee743706af)

**Actual behavior:  ❗️**
There's a bottom left and right border radius (Header is the one with the purple background)

**Possible Solution:**
Remove the bottom right and bottom left radius.

**Comment by ksdhir** [comment]
Fixed and closing.
