### ISSUE TITLE
Landing Page - Menu

### ISSUE THREAD

**Issue by Haidoe** [Haidoe/arc#267]
## Bug Report

**Reporter: ❗️**
 @Haidoe 

**Describe the bug: ❗️**
Menu items doesn't redirect to the proper section

**Steps to reproduce: ❗️**
1. Go to the landing page

**Screenshots or Video**

![Screenshot 2023-07-31 at 12 43 58 PM](https://github.com/Haidoe/arc/assets/20655791/756d7618-1910-43db-946e-431316b3871c)

**Expected behavior:  ❗️**
Transition to the proper section

**Actual behavior:  ❗️**
not doing anything

**Comment by ksdhir** [comment]
Fixed and closing.
