### ISSUE TITLE
Dashboard: Production progress chart alignment

### ISSUE THREAD

**Issue by kbmirambel** [Haidoe/arc#276]
## Bug Report

**Reporter: ❗️**
 @kbmirambel 

**Describe the bug: ❗️**
The infographic meter is not aligned with the legends below.

**Screenshots or Video**
<img width="997" alt="Screen Shot 2023-07-31 at 9 07 28 PM" src="https://github.com/Haidoe/arc/assets/123606372/52f109fb-cd3f-43e0-8293-a8497477ed35">

**Expected behavior:  ❗️**
<img width="380" alt="Screen Shot 2023-07-31 at 9 09 33 PM" src="https://github.com/Haidoe/arc/assets/123606372/a26d479d-3384-4c50-ac95-cc3846f9fbb0">

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by ksdhir** [comment]
@kbmirambel it looks aligned to me.
![Screenshot 2023-08-01 at 3 51 02 PM](https://github.com/Haidoe/arc/assets/44022086/48c73cc0-3f13-4ce7-b079-649f141c5ccb)


Can you provide steps to reproduce the issue?

**Comment by kbmirambel** [comment]
@ksdhir 
I was trying to resize the screen and it doesn't return to its first alignment.


https://github.com/Haidoe/arc/assets/123606372/3e156c9a-f5f7-4387-9e4a-408af378095d

**Comment by ksdhir** [comment]
@kbmirambel Oh i see. it's because you're testing it on arc-app.ca, I think it will work fine now. The production was not updated.

**Comment by kbmirambel** [comment]
Yes, I saw the production site now. Thank you @ksdhir
