### ISSUE TITLE
Landing Page: Include images for features

### ISSUE THREAD

**Issue by rafaelajung** [Haidoe/arc#280]
## Bug Report

**Reporter: ❗️**
 @rjung07 

**Describe the bug: ❗️**
The images of features are missing.

**Steps to reproduce: ❗️**

**Screenshots or Video**
![image](https://github.com/Haidoe/arc/assets/123789857/22b61467-8356-445e-9f7f-161d35cef82c)

**Expected behavior:  ❗️**

**Actual behavior:  ❗️**
A clear and concise description of what actually happened.

**Possible Solution:**
If you have any ideas or suggestions on how to fix the bug, please mention them here.

**Environment:**
- Device & Operating System:
- Browser and Version(if applicable):
- Jira Ticket(if applicable):
- Any other relevant information about your environment.

**Additional context:**

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
@rjung07 

Will assign it back to you until the design team provided the assets.

**Comment by Haidoe** [comment]
duplicate

https://github.com/Haidoe/arc/issues/243
