### ISSUE TITLE
Landing Page: change purple background for team part

### ISSUE THREAD

**Issue by rafaelajung** [Haidoe/arc#281]
## Bug Report

**Reporter: ❗️**
 @ksdhir

**Describe the bug: ❗️**
The background is too bright, eyes hurt.

**Steps to reproduce: ❗️**

**Screenshots or Video**
![image](https://github.com/Haidoe/arc/assets/123789857/061a4dd6-5efe-4b6a-bbf9-6e504f94f4af)

**Expected behavior:  ❗️**

**Actual behavior:  ❗️**
A clear and concise description of what actually happened.

**Possible Solution:**
If you have any ideas or suggestions on how to fix the bug, please mention them here.

**Environment:**
- Device & Operating System:
- Browser and Version(if applicable):
- Jira Ticket(if applicable):
- Any other relevant information about your environment.

**Additional context:**

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
was changed to dark purple
