### ISSUE TITLE
Productions page: Add possibility to delete a production

### ISSUE THREAD

**Issue by rafaelajung** [Haidoe/arc#282]
## Bug Report

**Reporter: ❗️**
 @rjung07 

**Describe the bug: ❗️**

**Steps to reproduce: ❗️**

**Screenshots or Video**
If applicable, add screenshots / video to help explain your problem.

**Expected behavior:  ❗️**

**Actual behavior:  ❗️**
A clear and concise description of what actually happened.

**Possible Solution:**
If you have any ideas or suggestions on how to fix the bug, please mention them here.

**Environment:**
- Device & Operating System:
- Browser and Version(if applicable):
- Jira Ticket(if applicable):
- Any other relevant information about your environment.

**Additional context:**

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
@jbsinluenam 

add an archive button beside the edit button of the sidebar.

**Comment by Haidoe** [comment]
will not implement.
