### ISSUE TITLE
Production page: hover states not working on navigation menu

### ISSUE THREAD

**Issue by rafaelajung** [Haidoe/arc#284]
## Bug Report

**Reporter: ❗️**
 @ksdhir

**Describe the bug: ❗️**
When hovering through the navigation menu, the state is now changing.

**Steps to reproduce: ❗️**

**Screenshots or Video**
![image](https://github.com/Haidoe/arc/assets/123789857/f31e3d19-8a7d-4cff-82ec-e5b18644ced0)

**Expected behavior:  ❗️**

**Actual behavior:  ❗️**
A clear and concise description of what actually happened.

**Possible Solution:**
If you have any ideas or suggestions on how to fix the bug, please mention them here.

**Environment:**
- Device & Operating System:
- Browser and Version(if applicable):
- Jira Ticket(if applicable):
- Any other relevant information about your environment.

**Additional context:**

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
duplicate
