### ISSUE TITLE
Dashboard: today button not working

### ISSUE THREAD

**Issue by rafaelajung** [Haidoe/arc#286]
## Bug Report

**Reporter: ❗️**
 @ksdhir

**Describe the bug: ❗️**
If it's not working, we should put the message that says is a future feature?

**Steps to reproduce: ❗️**

**Screenshots or Video**
![image](https://github.com/Haidoe/arc/assets/123789857/b9fa1f87-83b6-416d-8c69-1ab8798450eb)

**Expected behavior:  ❗️**

**Actual behavior:  ❗️**
A clear and concise description of what actually happened.

**Possible Solution:**
If you have any ideas or suggestions on how to fix the bug, please mention them here.

**Environment:**
- Device & Operating System:
- Browser and Version(if applicable):
- Jira Ticket(if applicable):
- Any other relevant information about your environment.

**Additional context:**

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
removed.
