### ISSUE TITLE
Dashboard: change download report button for share button like report

### ISSUE THREAD

**Issue by rafaelajung** [Haidoe/arc#287]
## Bug Report

**Reporter: ❗️**
 @ksdhir

**Describe the bug: ❗️**

**Steps to reproduce: ❗️**

**Screenshots or Video**
![image](https://github.com/Haidoe/arc/assets/123789857/44bfe176-4dc8-40a9-9a92-81bd42a403b0)

**Expected behavior:  ❗️**

**Actual behavior:  ❗️**
A clear and concise description of what actually happened.

**Possible Solution:**
If you have any ideas or suggestions on how to fix the bug, please mention them here.

**Environment:**
- Device & Operating System:
- Browser and Version(if applicable):
- Jira Ticket(if applicable):
- Any other relevant information about your environment.

**Additional context:**

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by Haidoe** [comment]
there will be no share report here.
