### ISSUE TITLE
Scene form : add scene shot to scene form

### ISSUE THREAD

**Issue by jbsinluenam** [Haidoe/arc#299]
## Bug Report

**Reporter: ❗️**
 @jbsinluenam 

**Describe the bug: ❗️**
No scene shot in scene form

**Follow up checklist:  ❗️**
- [x] #300
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by ksdhir** [comment]
Fixed and closing
